# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('integrantes', models.CharField(max_length=512)),
                ('fecha_inicio', models.DateTimeField()),
            ],
        ),
    ]
